# fly.toml app configuration file generated for tui-blog on 2025-01-01T20:18:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tui-blog'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 22
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
